// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package sqlite3

import (
	"syscall"
	"unsafe"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return nil
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modsqlite3 = syscall.NewLazyDLL("sqlite3.dll")

	procsqlite3_libversion           = modsqlite3.NewProc("sqlite3_libversion")
	procsqlite3_libversion_number    = modsqlite3.NewProc("sqlite3_libversion_number")
	procsqlite3_sourceid             = modsqlite3.NewProc("sqlite3_sourceid")
	procsqlite3_threadsafe           = modsqlite3.NewProc("sqlite3_threadsafe")
	procsqlite3_busy_timeout         = modsqlite3.NewProc("sqlite3_busy_timeout")
	procsqlite3_exec                 = modsqlite3.NewProc("sqlite3_exec")
	procsqlite3_errcode              = modsqlite3.NewProc("sqlite3_errcode")
	procsqlite3_extended_errcode     = modsqlite3.NewProc("sqlite3_extended_errcode")
	procsqlite3_errmsg               = modsqlite3.NewProc("sqlite3_errmsg")
	procsqlite3_errstr               = modsqlite3.NewProc("sqlite3_errstr")
	procsqlite3_open_v2              = modsqlite3.NewProc("sqlite3_open_v2")
	procsqlite3_close_v2             = modsqlite3.NewProc("sqlite3_close_v2")
	procsqlite3_backup_init          = modsqlite3.NewProc("sqlite3_backup_init")
	procsqlite3_backup_pagecount     = modsqlite3.NewProc("sqlite3_backup_pagecount")
	procsqlite3_backup_remaining     = modsqlite3.NewProc("sqlite3_backup_remaining")
	procsqlite3_backup_step          = modsqlite3.NewProc("sqlite3_backup_step")
	procsqlite3_backup_finish        = modsqlite3.NewProc("sqlite3_backup_finish")
	procsqlite3_get_autocommit       = modsqlite3.NewProc("sqlite3_get_autocommit")
	procsqlite3_prepare_v2           = modsqlite3.NewProc("sqlite3_prepare_v2")
	procsqlite3_limit                = modsqlite3.NewProc("sqlite3_limit")
	procsqlite3_finalize             = modsqlite3.NewProc("sqlite3_finalize")
	procsqlite3_bind_parameter_count = modsqlite3.NewProc("sqlite3_bind_parameter_count")
	procsqlite3_reset                = modsqlite3.NewProc("sqlite3_reset")
	procsqlite3_bind_parameter_index = modsqlite3.NewProc("sqlite3_bind_parameter_index")
	procsqlite3_bind_null            = modsqlite3.NewProc("sqlite3_bind_null")
	procsqlite3_bind_blob            = modsqlite3.NewProc("sqlite3_bind_blob")
	procsqlite3_bind_text            = modsqlite3.NewProc("sqlite3_bind_text")
	procsqlite3_bind_value           = modsqlite3.NewProc("sqlite3_bind_value")
	procsqlite3_bind_double          = modsqlite3.NewProc("sqlite3_bind_double")
	procsqlite3_bind_int             = modsqlite3.NewProc("sqlite3_bind_int")
	procsqlite3_bind_int64           = modsqlite3.NewProc("sqlite3_bind_int64")
	procsqlite3_column_count         = modsqlite3.NewProc("sqlite3_column_count")
	procsqlite3_interrupt            = modsqlite3.NewProc("sqlite3_interrupt")
	procsqlite3_clear_bindings       = modsqlite3.NewProc("sqlite3_clear_bindings")
	procsqlite3_step                 = modsqlite3.NewProc("sqlite3_step")
	procsqlite3_db_handle            = modsqlite3.NewProc("sqlite3_db_handle")
	procsqlite3_last_insert_rowid    = modsqlite3.NewProc("sqlite3_last_insert_rowid")
	procsqlite3_changes              = modsqlite3.NewProc("sqlite3_changes")
	procsqlite3_column_name          = modsqlite3.NewProc("sqlite3_column_name")
	procsqlite3_column_decltype      = modsqlite3.NewProc("sqlite3_column_decltype")
	procsqlite3_column_bytes         = modsqlite3.NewProc("sqlite3_column_bytes")
	procsqlite3_column_blob          = modsqlite3.NewProc("sqlite3_column_blob")
	procsqlite3_value_dup            = modsqlite3.NewProc("sqlite3_value_dup")
	procsqlite3_column_double        = modsqlite3.NewProc("sqlite3_column_double")
	procsqlite3_column_int64         = modsqlite3.NewProc("sqlite3_column_int64")
	procsqlite3_column_text          = modsqlite3.NewProc("sqlite3_column_text")
	procsqlite3_column_type          = modsqlite3.NewProc("sqlite3_column_type")
	procsqlite3_column_value         = modsqlite3.NewProc("sqlite3_column_value")
)

func sqlite3_libversion() (version string) {
	r0, _, _ := procsqlite3_libversion.Call()
	version = UintptrToString(r0)
	return
}

func sqlite3_libversion_number() (version int) {
	r0, _, _ := procsqlite3_libversion_number.Call()
	version = int(r0)
	return
}

func sqlite3_sourceid() (sourceidPtr string) {
	r0, _, _ := procsqlite3_sourceid.Call()
	sourceidPtr = UintptrToString(r0)
	return
}

func sqlite3_threadsafe() (isThreadSafe bool) {
	r0, _, _ := procsqlite3_threadsafe.Call()
	isThreadSafe = r0 != 0
	return
}

func sqlite3_busy_timeout(db sqlite3, ms int) (ret int) {
	r0, _, _ := procsqlite3_busy_timeout.Call(uintptr(db), uintptr(ms))
	ret = int(r0)
	return
}

func zsqlite3_exec() {
	procsqlite3_exec.Call()
	return
}

func sqlite3_errcode(db sqlite3) (errcode int) {
	r0, _, _ := procsqlite3_errcode.Call(uintptr(db))
	errcode = int(r0)
	return
}

func sqlite3_extended_errcode(db sqlite3) (errcode int) {
	r0, _, _ := procsqlite3_extended_errcode.Call(uintptr(db))
	errcode = int(r0)
	return
}

func sqlite3_errmsg(db sqlite3) (msg string) {
	r0, _, _ := procsqlite3_errmsg.Call(uintptr(db))
	msg = UintptrToString(r0)
	return
}

func sqlite3_errstr(err int) (errStrPtr string) {
	r0, _, _ := procsqlite3_errstr.Call(uintptr(err))
	errStrPtr = UintptrToString(r0)
	return
}

func zsqlite3_open_v2() {
	procsqlite3_open_v2.Call()
	return
}

func sqlite3_close_v2(db sqlite3) (ret int) {
	r0, _, _ := procsqlite3_close_v2.Call(uintptr(db))
	ret = int(r0)
	return
}

func zsqlite3_backup_init() {
	procsqlite3_backup_init.Call()
	return
}

func sqlite3_backup_pagecount(b sqlite3_backup) (ret int) {
	r0, _, _ := procsqlite3_backup_pagecount.Call(uintptr(b))
	ret = int(r0)
	return
}

func sqlite3_backup_remaining(b sqlite3_backup) (ret int) {
	r0, _, _ := procsqlite3_backup_remaining.Call(uintptr(b))
	ret = int(r0)
	return
}

func sqlite3_backup_step(b sqlite3_backup, page int) (ret int) {
	r0, _, _ := procsqlite3_backup_step.Call(uintptr(b), uintptr(page))
	ret = int(r0)
	return
}

func sqlite3_backup_finish(b sqlite3_backup) (ret int) {
	r0, _, _ := procsqlite3_backup_finish.Call(uintptr(b))
	ret = int(r0)
	return
}

func sqlite3_get_autocommit(db sqlite3) (ret int) {
	r0, _, _ := procsqlite3_get_autocommit.Call(uintptr(db))
	ret = int(r0)
	return
}

func zsqlite3_prepare_v2() {
	procsqlite3_prepare_v2.Call()
	return
}

func sqlite3_limit(db sqlite3, id int, newVal int) (ret int) {
	r0, _, _ := procsqlite3_limit.Call(uintptr(db), uintptr(id), uintptr(newVal))
	ret = int(r0)
	return
}

func sqlite3_finalize(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_finalize.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func sqlite3_bind_parameter_count(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_bind_parameter_count.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func sqlite3_reset(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_reset.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func zsqlite3_bind_parameter_index() {
	procsqlite3_bind_parameter_index.Call()
	return
}

func sqlite3_bind_null(stmt sqlite3_stmt, ordinal int) (ret int) {
	r0, _, _ := procsqlite3_bind_null.Call(uintptr(stmt), uintptr(ordinal))
	ret = int(r0)
	return
}

func zsqlite3_bind_blob() {
	procsqlite3_bind_blob.Call()
	return
}

func zsqlite3_bind_text() {
	procsqlite3_bind_text.Call()
	return
}

func sqlite3_bind_value(stmt sqlite3_stmt, ordinal int, val uintptr) (ret int) {
	r0, _, _ := procsqlite3_bind_value.Call(uintptr(stmt), uintptr(ordinal), uintptr(val))
	ret = int(r0)
	return
}

func zsqlite3_bind_double() {
	procsqlite3_bind_double.Call()
	return
}

func sqlite3_bind_int(stmt sqlite3_stmt, ordinal int, val int) (ret int) {
	r0, _, _ := procsqlite3_bind_int.Call(uintptr(stmt), uintptr(ordinal), uintptr(val))
	ret = int(r0)
	return
}

func sqlite3_bind_int64(stmt sqlite3_stmt, ordinal int, val int64) (ret int) {
	r0, _, _ := procsqlite3_bind_int64.Call(uintptr(stmt), uintptr(ordinal), uintptr(val))
	ret = int(r0)
	return
}

func sqlite3_column_count(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_column_count.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func sqlite3_interrupt(db sqlite3) {
	procsqlite3_interrupt.Call(uintptr(db))
	return
}

func sqlite3_clear_bindings(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_clear_bindings.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func sqlite3_step(stmt sqlite3_stmt) (ret int) {
	r0, _, _ := procsqlite3_step.Call(uintptr(stmt))
	ret = int(r0)
	return
}

func zsqlite3_db_handle() {
	procsqlite3_db_handle.Call()
	return
}

func sqlite3_last_insert_rowid(db sqlite3) (rowid int64) {
	r0, _, _ := procsqlite3_last_insert_rowid.Call(uintptr(db))
	rowid = int64(r0)
	return
}

func sqlite3_changes(db sqlite3) (changes int64) {
	r0, _, _ := procsqlite3_changes.Call(uintptr(db))
	changes = int64(r0)
	return
}

func sqlite3_column_name(stmt sqlite3_stmt, idx int) (name string) {
	r0, _, _ := procsqlite3_column_name.Call(uintptr(stmt), uintptr(idx))
	name = UintptrToString(r0)
	return
}

func sqlite3_column_decltype(stmt sqlite3_stmt, idx int) (name string) {
	r0, _, _ := procsqlite3_column_decltype.Call(uintptr(stmt), uintptr(idx))
	name = UintptrToString(r0)
	return
}

func sqlite3_column_bytes(stmt sqlite3_stmt, idx int) (ret int) {
	r0, _, _ := procsqlite3_column_bytes.Call(uintptr(stmt), uintptr(idx))
	ret = int(r0)
	return
}

func zsqlite3_column_blob() {
	procsqlite3_column_blob.Call()
	return
}

func sqlite3_value_dup(unprot_val uintptr) (prot_val uintptr) {
	r0, _, _ := procsqlite3_value_dup.Call(uintptr(unprot_val))
	prot_val = uintptr(r0)
	return
}

func zsqlite3_column_double() {
	procsqlite3_column_double.Call()
	return
}

func sqlite3_column_int64(stmt sqlite3_stmt, idx int) (ret int64) {
	r0, _, _ := procsqlite3_column_int64.Call(uintptr(stmt), uintptr(idx))
	ret = int64(r0)
	return
}

func zsqlite3_column_text() {
	procsqlite3_column_text.Call()
	return
}

func sqlite3_column_type(stmt sqlite3_stmt, idx int) (ret int) {
	r0, _, _ := procsqlite3_column_type.Call(uintptr(stmt), uintptr(idx))
	ret = int(r0)
	return
}

func sqlite3_column_value(stmt sqlite3_stmt, idx int) (ret uintptr) {
	r0, _, _ := procsqlite3_column_value.Call(uintptr(stmt), uintptr(idx))
	ret = uintptr(r0)
	return
}
